### ISSUE TITLE
Call to a member function getId() on null

### ISSUE THREAD

**Issue by meysammahfouzi** [octobercms/test-plugin#28]
Steps to replicate the problem (**October build number: 380**)

1. Install the plugin 
2. Click on the `Playground `link (top menu)
3. Click on the `Users` link (left side menu)
4. Click on the record with ID 2 (Username: Morpheus)
5. Click on the "`Pivot data`" tab
6. Click on the "`Create Role`" button
7. The following error happens:

> \<div id=""Call to a member function getId() on null" on line 1 of d:\projects\test-project\modules\backend\behaviors\relationcontroller\partials\_manage_form.htm

Why does this happen? I need to learn how to manage many to many relationships with pivot data, but this is failing.

**Comment by meysammahfouzi** [comment]
I upgraded to build 387 and the problem persists.

**Comment by pbsmultimedia** [comment]
Same here.

**Comment by faustoq** [comment]
@daftspunk please read this

**Comment by amorphine** [comment]
@daftspunk hello.
Thanks for this awesome demo-plugin.
P. S. Same issue. Bump

**Comment by daftspunk** [comment]
Probably a bit of confusion around this because of some assumed functionality that doesn't exist. The immediate error can be solved by adding a `manage.form` field definition:

**~/plugins/october/test/controllers/users/config_relation.yaml**
```
# ...

roles_pivot:
    label: Role
    view:
        list: ~/plugins/october/test/models/userrolepivot/columns.yaml
        showSearch: true
    manage:
        list: ~/plugins/october/test/models/role/columns.yaml
        form: ~/plugins/october/test/models/role/fields.yaml # <-- Added this line here

    pivot:
        form: ~/plugins/october/test/models/userrolepivot/fields.yaml
```

However, this creates a record and ignores the pivot data, which must be nullable in the database to function without error. There is also no way to manage the model data past the creation, only the pivot data. This workflow is confusing and not useful so for now we'll remove the "Create" button to prevent any further confusion.

Outlined below is a proposal that might allow the desired / assumed functionality. An issue should be created in the octobercms/october repo so it can be picked up and worked on. The issue needs to describe the use case beyond "it's a problem". The solution below assumes:

- Introduce feature to RelationController allowing dual form management for primary model and pivot model data.

Does it solve the problem?

#### Current functionality

1. Create button pressed
1. Popup appears with primary form
1. Form populated and saved
1. New record created (pivot data empty)

- There is no way to manage the primary form data

#### Assumed / ideal functionality

1. Create button pressed
1. Primary form **and pivot form** appear in the same popup (dual form popup)
1. Forms are populated and saved in one request
1. Primary model saved, model associated with data from pivot form
1. New record created along with pivot data

- Clicking on a record opens the dual form popup, allowing primary and pivot data to be managed
- A new mode is introduced so developer can choose precisely if they want just pivot, or pivot with primary
